blank_issues_enabled: true
contact_links:
  - name: SchoolRate Comunity
    url: https://discord.gg/sAderbAAtx
    about: Please ask and answer questions here.
  - name: SchoolRate support
    email: schoolrateapp@gmail.com
    about: Support email